version: '3.8'

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: konew_mailbox
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: ["/app/bin/konew", "start_iex"]
    container_name: konew_app
    restart: always
    depends_on:
      - mailpit
    ports:
      - "4000:4000"
    environment:
      - DB_ADAPTER=sqlite3
      - DATABASE_PATH=/app/data/konew_prod.db
      - PHX_HOST=192.168.100.11
      - PHX_SERVER=true
      - PORT=4000
      - SECRET_KEY_BASE="please run mix phx.gen.secret"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
