version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - elixir-deps:/workspace/deps
      - elixir-build:/workspace/_build
      - sqlite_data:/app/data
    ports:
      - "0.0.0.0:4000:4000"
    command: sleep infinity
    depends_on:
      - mailpit
    environment:
      - DATABASE_PATH=/app/data/konew_dev.db

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"

volumes:
  elixir-deps:
  elixir-build:
  sqlite_data:
